import globals from 'globals';
import eslint_js from '@eslint/js';
import prettier from 'eslint-config-prettier';

export default [
	{
		ignores: [ '.pnpm-store/*', 'php/*', 'pnpm-lock.yaml', 'types/*', 'vendor/*' ],
	},
	eslint_js.configs.recommended,
	{
		languageOptions: {
			ecmaVersion: 2022,
			sourceType: 'module',
			globals: {
				...globals.node,
			},
		},
		plugins: { prettier },
		rules: {
			'array-bracket-spacing': [ 'error', 'always' ],
			'array-callback-return': 'error',
			'arrow-parens': [ 'error', 'as-needed' ],
			'arrow-spacing': 'error',
			'brace-style': [ 'error', '1tbs' ],
			'comma-dangle': [ 'error', 'always-multiline' ],
			'comma-spacing': 'error',
			'comma-style': [ 'error', 'last' ],
			'computed-property-spacing': [ 'error', 'always' ],
			'constructor-super': 'error',
			'curly': [ 'error', 'all' ],
			'dot-notation': 'error',
			'eol-last': 'error',
			'eqeqeq': 'error',
			'func-call-spacing': 'error',
			'indent': [ 'error', 'tab', { SwitchCase: 1 } ],
			'key-spacing': 'error',
			'keyword-spacing': 'error',
			'linebreak-style': [ 'error', 'unix' ],
			'no-alert': 'error',
			'no-bitwise': 'error',
			'no-caller': 'error',
			'no-cond-assign': [ 'error', 'except-parens' ],
			'no-console': 'error',
			'no-const-assign': 'error',
			'no-debugger': 'error',
			'no-dupe-args': 'error',
			'no-dupe-class-members': 'error',
			'no-dupe-keys': 'error',
			'no-duplicate-case': 'error',
			'no-duplicate-imports': 'error',
			'no-else-return': 'error',
			'no-eval': 'error',
			'no-extra-semi': 'error',
			'no-fallthrough': 'error',
			'no-irregular-whitespace': 'error',
			'no-lonely-if': 'error',
			'no-mixed-operators': 'error',
			'no-mixed-spaces-and-tabs': 'error',
			'no-multi-spaces': 'error',
			'no-multi-str': 'error',
			'no-multiple-empty-lines': [ 'error', { max: 1 } ],
			'no-nested-ternary': 'error',
			'no-redeclare': 'error',
			'no-shadow': 'error',
			'no-trailing-spaces': 'error',
			'no-undef-init': 'error',
			'no-undef': 'error',
			'no-unreachable': 'error',
			'no-unsafe-negation': 'error',
			'no-unused-expressions': 'error',
			'no-unused-vars': [ 'error', { ignoreRestSiblings: true } ],
			'no-useless-computed-key': 'error',
			'no-useless-constructor': 'error',
			'no-useless-return': 'error',
			'no-var': 'error',
			'no-whitespace-before-property': 'error',
			'no-with': 'error',
			'object-curly-spacing': [ 'error', 'always' ],
			'object-shorthand': 'error',
			'one-var-declaration-per-line': [ 'error', 'initializations' ],
			'operator-linebreak': 'error',
			'padded-blocks': [ 'error', 'never' ],
			'prefer-const': [ 'error', { destructuring: 'all' } ],
			'quote-props': [ 'error', 'consistent' ],
			'quotes': [ 'error', 'single', { allowTemplateLiterals: true, avoidEscape: true } ],
			'semi-spacing': 'error',
			'semi': [ 'error', 'always' ],
			'space-before-blocks': [ 'error', 'always' ],
			'space-before-function-paren': [ 'error', { anonymous: 'never', named: 'never', asyncArrow: 'always' } ],
			'space-in-parens': [ 'error', 'always' ],
			'space-infix-ops': 'error',
			'space-unary-ops': [ 'error', { overrides: { '!': true, 'yield': true } } ],
			'template-curly-spacing': [ 'error', 'always' ],
			'valid-typeof': 'error',
			'vars-on-top': 'off',
			'wrap-iife': 'error',
		},
	},
];
